### ISSUE TITLE
onRoomDidConnect get called on Debug but not on Release APK

### ISSUE THREAD

**Issue by 1stblood** [blackuy/react-native-twilio-video-webrtc#591]
### Steps to reproduce
1. run npx react-native run-android
2. twilioRef.current.connect({accessToken: token)} - Get Video on Both Party well (Debug) but not on Release.
3. Code:
` useEffect(() => {
        let isMounted = true
        if (isMounted) {
            console.log('VideoKonsul', status)
            const PermissionRequest = async () => {
                await _requestAudioPermission();
                await _requestCameraPermission();
            }
            PermissionRequest()
            const confirmChat = () => {
                let data = {
                    consultation_code: consultation,
                    mode: 'accept',
                };
                fetch('https://cms.klinis.co.id/api/consultation/patient/confirm', {
                    method: "POST",
                    headers: {
                        Authorization: 'Bearer ' + token,
                        Accept: 'application/json',
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(data)
                })
                    .then(response => response.json())
                    .then(responseJson => {
                        console.log('konsultasimode', responseJson)
                    })
            }

            const createRoom = () => {
                let chatRoom = {
                    consultation_code: consultation,
                    username: fullname,
                }
                fetch('https://cms.klinis.co.id/api/consultation/patient/room', {
                    method: "POST",
                    headers: {
                        Authorization: 'Bearer ' + token,
                        Accept: 'application/json',
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(chatRoom)
                })
                    .then(response => response.json())
                    .then(async responseJson => {
                        // console.log('roomIDN', responseJson.room.roomID)
                        await getToken(responseJson.room.roomID)
                        setRoomID(responseJson.room.roomID)
                    })
            }

            const getToken = (roomer) => {
                console.log('roomer', roomer, fullname)
                fetch(`http://54.251.xx.xxx.:3403/token?identity=${fullname}=&room=${roomer}`)
                    .then(response => response.json())
                    .then(responseJson => {
                        // console.log('corstwilio', responseJson)
                        setAccessToken(responseJson.token)
                    })
            }
            createRoom()
            confirmChat()
            twilioRef.current.connect({accessToken: accessToken})
            setOverlayModal(true)

  {
                status === 'disconnected' &&
                <View style={{ margin: 20, flex: 1 }}>
                    <View style={{ flex: 1 }}>
                        <Center>
                            <Text style={styles.welcome}>Telekonsultasi Video</Text>
                            <LottieView
                                source={require('../../assets/doctor-waiting.json')}
                                autoPlay
                                loop
                                style={{ width: 300, height: 300 }}
                            />
                            <Text style={{ fontFamily: 'poppins-regular', color: "#333" }}>Hi, <Text style={{ fontFamily: 'poppins-bold' }}>{fullname},</Text></Text>
                            <Text style={{ fontFamily: 'poppins-regular', fontSize: 13, color: "#333" }}>Mohon tunggu sebentar, {namaDokter} akan segera menjawab pertanyaan konsultasi anda.</Text>

                        </Center>
                    </View>
                    <View>
                        <Text style={{ fontFamily: 'poppins-light', fontSize: 10, marginTop: 10, color: "#999", marginBottom: 10, textAlign: 'center' }}>Jika anda sudah siap, silahkan tekan tombol dibawah ini untuk memulai Telekonsultasi Video</Text>
                        <Button style={{ alignItems: 'flex-end' }} size="md" style={{ backgroundColor: "#0eabaa" }} onPress={() => {
                            fetch(`https://cms.klinis.co.id/api/consultation/patient/history/detail?consultation_code=${consultation}`, {
                                headers: {
                                    Authorization: 'Bearer ' + token,
                                    Accept: 'application/json',
                                    'Content-Type': 'application/json',
                                },
                            })
                                .then(response => response.json())
                                .then(responseJson => {
                                    console.log('checkbayar', responseJson)
                                    if (responseJson.transaction_status == 'Approve' && responseJson.status == 'Completed') {
                                        twilioRef.current.connect({accessToken: accessToken})
                                        setStatus('connecting');
                                        clearTimer(getDeadTime());
                                    } else {
                                        Alert.alert(
                                            'Dokter Belum Memasuki Ruangan',
                                            `${namaDokter} belum memasuki Ruangan Telekonsultasi Ini. Silahkan tunggu beberapa saat lagi.`,
                                            [{ text: 'OK', onPress: () => console.log('OK') }],
                                        );
                                    }
                                })
                                .catch(e => alert(e))
                        }}>Mulai Telekonsultasi</Button>
                    </View>
                </View>
            }

---- the rest of the code..... ----
`

### Expected behaviour
twilioRef.current.connect doesnt init the onDidConnect call

### Actual behaviour
No Participant Video nor Client on Room

_onDidConnect doesnt fire or twilioRef.current.connect doesnt called.

### Environment
- **Node.js version**: v17.0.1
- **React Native version**: 0.66.1
- **React Native platform + platform version**: Android 11

### react-native-twilio-video-webrtc
**Version**: npm version or "master" Latest 2.20

**Comment by slycoder** [comment]
Working in dev and not working in prod often speaks to a race condition.  I noticed that in a few places you were making calls without actually ensuring the previous promises were resolved.  I would consider adding some logging to ensure that events are actually occurring in the order you expect them to, and to be more consistent in your use of promises/await/async.

**Comment by 1stblood** [comment]
hi, @slycoder thanks for the comment. I actualy pass the token as params in _onConnectButtonPress.. On Debug mode it works flawlessly. I thinks it because race condition you mention. But i have clean up some codes with just passing / fetching API for token and roomName, on passing it into _onConnectButton press in Production still doesnt kicking the onRoomDidConnect.

Does it have something to do with the Reff or anything elsel, or maybe you could shed some light about what it doesnt connect on production

`const createRoom = () => {
                let chatRoom = {
                    consultation_code: consultation,
                    username: fullname,
                }
                fetch('https://cms.klinis.co.id/api/consultation/patient/room', {
                    method: "POST",
                    headers: {
                        Authorization: 'Bearer ' + token,
                        Accept: 'application/json',
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(chatRoom)
                })
                    .then(response => response.json())
                    .then(async responseJson => {
                        console.log('roomIDN', responseJson.room.roomID)
                        await getToken(responseJson.room.roomID)
                        setRoomID(responseJson.room.roomID)
                    })
            }

            const getToken = (roomer) => {
                console.log('roomer', roomer, fullname)
                fetch(`http://54.251.173.71:3403/token?identity=${fullname}=&room=${roomer}`)
                    .then(response => response.json())
                    .then(async responseJson => {
                        console.log('corstwilio', responseJson)
                        setAccessToken(responseJson.token)
                        await _onConnectButtonPress(responseJson.token,roomer)
                    })
            }
            const _onConnectButtonPress = async(tokenVids, roomer) => {
                if(Platform.OS == 'android'){
                    await _requestAudioPermission();
                    await _requestCameraPermission();
                }
                twilioRef.current.connect({
                    accessToken: tokenVids,
                    roomName: roomer
                })
                setStatus('connecting');
                clearTimer(getDeadTime());
            };`

**Comment by 1stblood** [comment]
I have solved the problem. Apparently due to Android restriction cannot resolve from HTTP connection on release version

My token get from http connection. Thanks

**Comment by Nziranziza** [comment]
I am having similar issue even if I am able to fetch the token

**Comment by pierroo** [comment]
> I have solved the problem. Apparently due to Android restriction cannot resolve from HTTP connection on release version
> 
> My token get from http connection. Thanks

would you mind sharing how did  you actuall solve the issue?

**Comment by dnx-xy** [comment]
Just enable http traffic true in Android.xml
