### ISSUE TITLE
Black screen after connect on android

### ISSUE THREAD

**Issue by atallahquaider** [blackuy/react-native-twilio-video-webrtc#94]
### Steps to reproduce
1. Create a new room
2. Join to the created room
3. Check if video working from remote track

### Expected behaviour
get the video with audio from remote twilio room

### Actual behaviour
I'm getting the audio only, but TwilioVideoParticipantView is black. On iOS both audio and video works fine.

### Environment
- **Node.js version**: 9.5
- **React Native version**: 0.52.3
- **React Native platform + platform version**: Android 6.0 API 26

The issue is similar to #86 but I can't downgrade my environment.

**Comment by slycoder** [comment]
Just to confirm, is this still a problem, even after pulling down the branch mentioned in #86 ?

**Comment by sohams89** [comment]
Facing same issue in android.

"react": "^16.6.3",
"react-native": "^0.57.7",
"react-native-twilio-video-webrtc": "git+https://github.com/blackuy/react-native-twilio-video-webrtc.git",

**Comment by fahidmohammad** [comment]
Any Update on this issue?
Facing the same problem on Android. (Black Screen on **TwilioVideoLocalView**)

**Version:**
- "react-native-twilio-video-webrtc"":react-native-twilio-video-webrtc@1.0.2
- "react": "16.6.3",
- "react-native": "0.57.8",

**Comment by FeMaffezzolli** [comment]
Facing same issue here on android. (black sreen on **TwilioVideoParticipantView** component)

-     "react": "^16.8.3",
-     "react-native": "^0.59.9",
-     "react-native-twilio-video-webrtc": "https://github.com/blackuy/react-native-twilio-video-webrtc",

**Comment by slycoder** [comment]
Out of curiosity what devices are people connecting to on the other end?  Could it be some codec compatibility issue? https://www.twilio.com/docs/video/managing-codecs

**Comment by FeMaffezzolli** [comment]
In my case I had a browser Chrome 57+ on the other end. In theory it should work fine, right?

**Comment by slycoder** [comment]
Hm, I think so?  Is there a repro you could share? Maybe something about the way you're rendering the participant view is tickling some error.  

Also is there anything in the logcat logs that looks suspicious?

**Comment by rolivegab** [comment]
Same issue here, and i think that is not a codec's problem.
I couldn't find any useful log on logcat.

**Comment by steelbrain** [comment]
Fixed Android black screen with https://github.com/blackuy/react-native-twilio-video-webrtc/commit/971220fcce3022b394697350b1244909861ac333 in https://github.com/blackuy/react-native-twilio-video-webrtc/pull/289

**Comment by slycoder** [comment]
For the people who have run into this issue, could they pull down @steelbrain 's branch and see if that fixes it?

**Comment by rolivegab** [comment]
It solved!
Thank you!

**Comment by pksingh123** [comment]
I am stuck with this issue, in both android and IOS participant view is black. Other's side video is not showing, audio is working. Calling between Web and Phone (android ).

```
 _onParticipantAddedVideoTrack = ({ participant, track }) => {
    //console.warn("onParticipantAddedVideoTrack: ", participant, track)
    console.log("conference 10 ", participant, track);
    this.setState({
      videoTracks: new Map([
        ...this.state.videoTracks,
        [track.trackSid, { participantSid: participant.sid, videoTrackSid: track.trackSid }]
      ]),
    });

    this.setState({
      trackSid: track.trackSid, isParticipant: true,
      trackIdentifier: { participantSid: participant.sid, videoTrackSid: track.trackSid }
    });

  }
```

```
<TwilioVideoParticipantView
          style={styles.remoteVideo}
          key={this.state.trackSid}
          enabled={true}
          trackIdentifier={this.state.trackIdentifier}
        />
```

getting no error. values are coming in _onParticipantAddedVideoTrack. other callbacks are working.

**Comment by slycoder** [comment]
Which web client are you using?  Do device-to-device connections work?

**Comment by FeMaffezzolli** [comment]
I got it solved here. Thanks!

**Comment by pksingh123** [comment]
> I got it solved here. Thanks!

hey @FeMaffezzolli how you solved it. can you please guide me.

**Comment by FeMaffezzolli** [comment]
> > I got it solved here. Thanks!
> 
> hey @FeMaffezzolli how you solved it. can you please guide me.

Of course pksingh123. In my case, after hours spent investigating this issue, I realized that the problem was never at my mobile app code. It was actually a problem at the sender endpoint (which in my case is a frontend app written in VueJS). The code there was not well implemented. I made a few mistakes regarding diferences between V 1.X and V 2.X of Twilio SDK docs. This piece helped me a lot: https://www.twilio.com/docs/video/migrating-1x-2x

I hope this information could help you. I'll share my final mobile app code anyway hoping it may help.

One important thing to mention is that my video screen receives the twilio Token as a prop. So you'll see that connection to the room happens immediately when the component mounts.

````
import React, { Component } from 'react';
import { StackActions, NavigationActions } from "react-navigation";
import { Toast, Icon } from "native-base";
import { StyleSheet, Text, View, TouchableOpacity, ActivityIndicator, Alert, Linking, Image } from 'react-native';
import { TwilioVideoLocalView, TwilioVideoParticipantView, TwilioVideo } from 'react-native-twilio-video-webrtc'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'
  },
  logo: {
    position: "absolute",
    top: 5,
    left: 5,
    maxWidth: 40,
    zIndex: 100,
  },
  callContainer: {
    flex: 1,
    position: "absolute",
    bottom: 0,
    top: 0,
    left: 0,
    right: 0
  },
  welcome: {
    fontSize: 30,
    textAlign: 'center',
    paddingTop: 40
  },
  input: {
    height: 50,
    borderWidth: 1,
    marginRight: 70,
    marginLeft: 70,
    marginTop: 50,
    textAlign: 'center',
    backgroundColor: 'white'
  },
  button: {
    marginTop: 100
  },
  localVideo: {
    flex: 1,
    width: 150,
    height: 210,
    position: "absolute",
    right: 10,
    bottom: 100
  },
  remoteGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: 'wrap'
  },
  remoteVideo: {
    flex: 1
    // marginTop: 0,
    // marginLeft: 10,
    // marginRight: 10,
    // width: 100,
    // height: 120,
  },
  optionsContainer: {
    position: "absolute",
    left: 0,
    bottom: 0,
    right: 0,
    height: 100,
    backgroundColor: 'transparent',
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center"
  },
  helpContainer: {
    position: "absolute",
    left: 0,
    bottom: 100,
    right: 0,
    height: 100,
    backgroundColor: 'transparent',
    flexDirection: "row",
    alignItems: "center"
  },
  optionButton: {
    width: 50,
    height: 50,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 100 / 2,
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignItems: "center"
  },
  helpButton: {
    width: 140,
    height: 60,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 100 / 2,
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignItems: "center"
  }
});

export default class VideoAppointment extends Component {
  constructor(props){
    super(props)
    this.state = {
      isAudioEnabled: true,
      isVideoEnabled: true,
      status: 'disconnected',
      participants: new Map(),
      videoTracks: new Map(),
      roomName: '',
      token: this.props.navigation.getParam('token')
    }
  }

  componentDidMount() {
    this._onConnectButtonPress();
  }

  _goBack() {
    const { navigation } = this.props;
    navigation.goBack();
  }

  _goHome() {
    const { navigation } = this.props;
    const resetAction = StackActions.reset({
      index: 0,
      actions: [
          NavigationActions.navigate({ routeName: 'SuccessScreen' })
      ],
    })
    navigation.dispatch(resetAction)
  }

  _goSuccessScreenThenHome() {
    const { navigation } = this.props;
    return navigation.push('SuccessScreen')
  }

  _onConnectButtonPress = () => {
    this.refs.twilioVideo.connect({ roomName: this.state.roomName, accessToken: this.state.token })
    this.setState({status: 'connecting'})
  }

  _onHelpButtonPress = () => {
    Alert.alert(
      'Confirmação',
      'A consulta será aberta no navegador do seu celular',
      [
        {text: 'Cancelar', onPress: () => {}, style: 'cancel'},
        {text: 'Ok', onPress: () => {
          Linking.openURL(`OPENS_ANOTHER_URL`)
            .then(() => {
              this._goHome()
            })
            .catch(() => {
              Toast.show({
                type: "warning",
                duration: 3000,
                text: "Não foi possível abrir o navegador do seu celular."
              });
            })
        }},
      ],
      { cancelable: false }
    )
  }

  _onEndButtonPress = () => {
    Alert.alert(
      'Confirmação',
      'Você realmente deseja sair da sala?',
      [
        {text: 'Cancelar', onPress: () => {}, style: 'cancel'},
        {text: 'Sair', onPress: () => {
          this.refs.twilioVideo.disconnect()
          this._goSuccessScreenThenHome()
        }},
      ],
      { cancelable: false }
    )
  }

  _onHideButtonPress = () => {
    this.refs.twilioVideo.setLocalVideoEnabled(!this.state.isVideoEnabled)
      .then(isEnabled => this.setState({isVideoEnabled: isEnabled}))
  }

  _onMuteButtonPress = () => {
    this.refs.twilioVideo.setLocalAudioEnabled(!this.state.isAudioEnabled)
      .then(isEnabled => this.setState({isAudioEnabled: isEnabled}))
  }

  _onFlipButtonPress = () => {
    this.refs.twilioVideo.flipCamera()
  }

  _onRoomDidConnect = () => {
    this.setState({status: 'connected'})
  }

  _onRoomDidDisconnect = ({roomName, error}) => {
    console.log("ERROR: ", error)
    this._goSuccessScreenThenHome()
    // this.setState({status: 'disconnected'})
  }

  _onRoomDidFailToConnect = (error) => {
    console.log("ERROR: ", error)

    this.setState({status: 'disconnected'})
    this._goBack()
  }

  _onParticipantAddedVideoTrack = ({participant, track}) => {
    console.log("onParticipantAddedVideoTrack: ", participant, track)

    this.setState({
      videoTracks: new Map([
        ...this.state.videoTracks,
        [track.trackSid, { participantSid: participant.sid, videoTrackSid: track.trackSid }]
      ]),
    });
  }

  _onParticipantRemovedVideoTrack = ({participant, track}) => {
    console.log("onParticipantRemovedVideoTrack: ", participant, track)

    const videoTracks = this.state.videoTracks
    videoTracks.delete(track.trackSid)

    this.setState({ videoTracks: new Map([ ...videoTracks ]) });
  }

  render() {
    return (
      <View style={styles.container}>
        <Image style={styles.logo} source={require('../../../../../assets/icon.png')} />
        {
          this.state.status === 'disconnected' && (
          // ##########################################################
          // ORIGINAL CODE WAS COMMENTED BECAUSE TOKEN AND ROOM NAME
          // WILL BE RECEIVED BY PROPS AND USED ON COMPONENT DID MOUNT
          // ##########################################################
          //
          // <View>
          //   <Text style={styles.welcome}>
          //     React Native Twilio Video
          //   </Text>
          //   <TextInput
          //     style={styles.input}
          //     autoCapitalize='none'
          //     value={this.state.roomName}
          //     onChangeText={(text) => this.setState({roomName: text})}>
          //   </TextInput>
          //   <TextInput
          //     style={styles.input}
          //     autoCapitalize='none'
          //     value={this.state.token}
          //     onChangeText={(text) => this.setState({token: text})}>
          //   </TextInput>
          //   <Button
          //     title="Connect"
          //     style={styles.button}
          //     onPress={this._onConnectButtonPress}>
          //   </Button>
          // </View>
          <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <ActivityIndicator size="large" color="#75F0A0" />
          </View>)
        }

        {
          (this.state.status === 'connected' || this.state.status === 'connecting') && (
            <View style={styles.callContainer}>
            {
              this.state.status === 'connected' && (
              <View style={styles.remoteGrid}>
                {
                  this.state.videoTracks.size ? (
                    Array.from(this.state.videoTracks, ([trackSid, trackIdentifier]) => {
                      // console.log('videoTracks tracksid: ', trackSid)
                      // console.log('videoTracks trackIdentifier: ', trackIdentifier)
                      return (
                        <TwilioVideoParticipantView
                          style={styles.remoteVideo}
                          key={trackSid}
                          trackIdentifier={trackIdentifier}
                        />
                      )
                    })
                  ) : (
                    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
                      <Text style={{fontSize: 16, color: '#0664BE', fontWeight: 'bold'}}>Aguardando o médico entrar ...</Text>
                    </View>
                  )
                }
              </View>)
            }
            <View
              style={styles.optionsContainer}>
              <TouchableOpacity
                style={[styles.optionButton, { backgroundColor: '#0664BE' }]}
                onPress={this._onHideButtonPress}>
                <Icon
                  name={this.state.isVideoEnabled ? "video" : "video-slash"}
                  type="FontAwesome5"
                  style={{color: "#FFF", fontSize: 18}}
                  // fontSize={10}
                />
                {/* <Text style={{fontSize: 12, color: '#FFF', fontWeight: 'bold'}}>Hide</Text> */}
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.optionButton, { backgroundColor: '#0664BE' }]}
                onPress={this._onMuteButtonPress}>
                <Icon
                  name={this.state.isAudioEnabled ? "microphone" : "microphone-slash"}
                  type="FontAwesome5"
                  style={{color: "#FFF", fontSize: 22}}
                  // fontSize={10}
                />
                {/* <Text style={{fontSize: 12, color: '#FFF', fontWeight: 'bold'}}>{ this.state.isAudioEnabled ? "Mudo" : "Som" }</Text> */}
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.optionButton, { backgroundColor: '#FF0026' }]}
                onPress={this._onEndButtonPress}>
                <Icon
                  name="phone-hangup"
                  type="MaterialCommunityIcons"
                  style={{color: "#FFF"}}
                  fontSize={12}
                />
                {/* <Text style={{fontSize: 12, color: '#FFF', fontWeight: 'bold'}}>Sair</Text> */}
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.optionButton, { backgroundColor: '#0664BE' }]}
                onPress={this._onFlipButtonPress}>
                <Icon
                  name="retweet"
                  type="FontAwesome5"
                  style={{color: "#FFF", fontSize: 22}}
                  // fontSize={10}
                />
                {/* <Text style={{fontSize: 12, color: '#FFF', fontWeight: 'bold'}}>Inverter</Text> */}
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.optionButton, { backgroundColor: '#0664BE' }]}
                onPress={this._onHelpButtonPress}>
                <Icon
                  name="share-square"
                  type="FontAwesome5"
                  style={{color: "#FFF", fontSize: 22}}
                  // fontSize={10}
                />
              </TouchableOpacity>
            </View>
            <TwilioVideoLocalView
              enabled={true}
              style={styles.localVideo}
            />
          </View>)
        }

        <TwilioVideo
          ref="twilioVideo"
          onRoomDidConnect={ this._onRoomDidConnect }
          onRoomDidDisconnect={ this._onRoomDidDisconnect }
          onRoomDidFailToConnect= { this._onRoomDidFailToConnect }
          onParticipantAddedVideoTrack={ this._onParticipantAddedVideoTrack }
          onParticipantRemovedVideoTrack= { this._onParticipantRemovedVideoTrack }
        />
      </View>
    );
  }
}
````

**Comment by diegomichell** [comment]
I'm still getting this issue on Android, has any found a solution?, It doesn't always happen to me, to me it happen when I'm on a video call and leave and then try to join again or join another video call

**Comment by Balasnest** [comment]
As @diegomichell said, it's happening in android devices. It's not happening at first call. but in the next recurrent call (**black screen**) and even taking more time (30 sec) to display participant video (participant is already joined)

**Comment by slycoder** [comment]
Thanks for the detailed investigation @Balasnest !  Do you happen to know if there's anything in the logcat that might be of interest?  I'm digging through the twilio quickstart issues to see if there's anything there that might be similar.  The only other thing I can think of is that some resources may not be correctly disposed.

**Comment by Balasnest** [comment]
@slycoder I am going to reproduce again to get the logcat. will share if I get it.

**Comment by Balasnest** [comment]
@slycoder This issue is happening everytime. There is a huge delay after participant connected. Anything can be done for this?
Logs: Couldn't get the better one. will share a few more logs.
---- [log.txt](https://github.com/blackuy/react-native-twilio-video-webrtc/files/4851399/log.txt)
